/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi1;

/**
 *
 * @author U S E R
 */
public class vendorK extends javax.swing.JFrame {

    /**
     * Creates new form vendorK
     */
    public vendorK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jbar = new javax.swing.JButton();
        jtimur = new javax.swing.JButton();
        jtengah1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 205, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 205, 232));
        jButton1.setFont(new java.awt.Font("212 Queenie Sans", 0, 36)); // NOI18N
        jButton1.setText("Wedcores");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 205, 232));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jteng (1).jpeg"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 190, 130));

        jButton4.setBackground(new java.awt.Color(255, 205, 232));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jawa timur5 (1).jpg"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 190, 130));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel3.setText("Vendors");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 205, 232));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jawa barat.jpg"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 130));

        jbar.setBackground(new java.awt.Color(255, 205, 232));
        jbar.setText("Jawa Barat");
        jbar.setBorderPainted(false);
        jbar.setContentAreaFilled(false);
        jbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarActionPerformed(evt);
            }
        });
        jPanel1.add(jbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jtimur.setBackground(new java.awt.Color(255, 205, 232));
        jtimur.setText("Jawa Timur");
        jtimur.setBorderPainted(false);
        jtimur.setContentAreaFilled(false);
        jtimur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtimurActionPerformed(evt);
            }
        });
        jPanel1.add(jtimur, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jtengah1.setBackground(new java.awt.Color(255, 205, 232));
        jtengah1.setText("Jawa Tengah");
        jtengah1.setBorderPainted(false);
        jtengah1.setContentAreaFilled(false);
        jtengah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtengah1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtengah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jtimur jtm = new jtimur();
        jtm.setLocationRelativeTo(null);
        jtm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        total t = new total();
        t.setLocationRelativeTo(null);
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jtengah jt = new jtengah();
        jt.setLocationRelativeTo(null);
        jt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jbarat jr = new jbarat();
        jr.setLocationRelativeTo(null);
        jr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarActionPerformed
        // TODO add your handling code here:
        jbarat jr = new jbarat();
        jr.setLocationRelativeTo(null);
        jr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbarActionPerformed

    private void jtimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtimurActionPerformed
        // TODO add your handling code here:
        jtimur jtm = new jtimur();
        jtm.setLocationRelativeTo(null);
        jtm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jtimurActionPerformed

    private void jtengah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtengah1ActionPerformed
        // TODO add your handling code here:
        jtengah jt = new jtengah();
        jt.setLocationRelativeTo(null);
        jt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jtengah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendorK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendorK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendorK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendorK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendorK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbar;
    private javax.swing.JButton jtengah1;
    private javax.swing.JButton jtimur;
    // End of variables declaration//GEN-END:variables
}
